### ISSUE TITLE
Empty Readme!!

### ISSUE THREAD

**Issue by UwUCatGirlMeow** [NCXT5/NXE#1]

**Comment by ghost** [comment]
K ill add a temp one

**Comment by decahedron1** [comment]
![image](https://user-images.githubusercontent.com/61946759/200981389-eb48b6f9-5b78-49a8-911d-a9a9292d3e08.png)

**Comment by ghost** [comment]
ye ik, im testing automation

**Comment by ghost** [comment]
funny tho xD

**Comment by ghost** [comment]
it would look weird if i just accepted the PR with no comment lmao

**Comment by ghost** [comment]
I assume u thugh this is my acc coz of https://github.com/community/community/discussions/38173

**Comment by decahedron1** [comment]
Well, it *is* your account

**Comment by ghost** [comment]
yes? Whats your point tho

**Comment by ghost** [comment]
@sudo-carson im killing this shit too, good bye
